### ISSUE TITLE
how each instance of cluster server for different conf

### ISSUE THREAD

**Issue by lintanghui** [moiot/gravity#87] opened 2019-02-19 02:27 UTC
If deploy in cluster mode, how can i distribute different  toml config to different.
eg:if i had 10 different mysql2mysql.toml config file and depley cluster with 10 instances. how each instance server only for one mysql.toml in case of duplicate sync.

**Comment by Ryan-Git** [comment] 2019-02-19 03:41
are you using [gravity-operator](https://github.com/moiot/gravity-operator) or a self managed cluster?
for gravity-operator, you can create pipeline on web, see the notes after installation. otherwise there's `-config` parameter assign the path to config file.

**Comment by lintanghui** [comment] 2019-02-19 10:04
that mean i should specific different -conf arg for different instance?  It seem complex for op, and if add more config file ,i should change the -config arg.it's that any possiblity of auto distribution for adding more config files without changing -config parameter.otherwise it seem terrible to maintained

**Comment by Ryan-Git** [comment] 2019-02-19 10:13
no. you could put each config file in its own directory, make a bash/docker/docker-compose to run it. and use ansible to manage all pipelines. the conf args are relative path and identical.
the difficult part is port assigning will either be done by human or need a service discovery mechanism.

It was our most original approach. It worked well for about tens of pipelines.

for hundreds of pipelines like we handle nowadays, an orchestration system is needed. k8s is our choice. (We had an etcd based cluster, but the resource scheduling functionality is much duplicate of k8s)

**Comment by lintanghui** [comment] 2019-02-19 11:55
it's that mean i should put config file to instance's directory by human? and if i want to scale instances, I should reput config file to their own directory? how can i konw how many config files should be put to each instance

**Comment by Ryan-Git** [comment] 2019-02-19 12:32
> it's that mean i should put config file to instance's directory by human?

No. you could put all config files in a git repo, use ansible to copy it to target machine.

> if i want to scale instances, I should reput config file to their own directory? how can i konw how many config files should be put to each instance

What do you mean by scale? One process accept just one config.

**Comment by lintanghui** [comment] 2019-02-19 14:13
> use ansible to copy it to target machine.

that mean i should define which file should  be copy to which target machine in ansible?
> One process accept just one config.

if i want to add more config files, i should setup up more instance for each config file?

**Comment by Ryan-Git** [comment] 2019-02-20 02:46
both are true.

One instance/process can only read input from one datasource instance and write to another(can be the same) one.

Our philosophy is first build a command line tool, then leverage k8s to provide cluster functionality based on it.

**Comment by lintanghui** [comment] 2019-02-20 03:11
and one more question. how did you define resource uint? and if new config file is added, how did you know how many resources is needed for the new instace(eg:0.5c0.5g ?) is there  any standard for resource allocation.

**Comment by Ryan-Git** [comment] 2019-02-20 06:45
it varies on workload and configuration. In our typical streaming pipeline, the process uses 1c 0.5g for approximately 5k tps. Batch mode needs more.

It's ok to start with default and turning according to the metrics.

**Closed as completed** 2019-02-21 10:04 UTC
